import { test, expect } from '@playwright/test';
import { generateTestEmail } from '../utils/auth-helpers';

/**
 * STRESS TEST: Motor Unificado - Membros 1 a 10
 * Este teste valida a capacidade de diferentes membros (Admins e Profissionais)
 * de processarem serviços variados vindos de clientes externos.
 */

const MEMBERS = [
  { email: 'membro1@fotosegundo.com.br', service: 'Checkout Memory (Turismo)' },
  { email: 'membro2@fotosegundo.com.br', service: 'Evento Social/Festa (4h)' },
  { email: 'membro3@fotosegundo.com.br', service: 'Ensaio Gastronômico Express' },
  { email: 'membro4@fotosegundo.com.br', service: 'Reels / Stories' },
  { email: 'membro5@fotosegundo.com.br', service: 'Vídeo Cinema' },
  { email: 'membro6@fotosegundo.com.br', service: 'Ativação Phygital Corporativa' },
  { email: 'membro7@fotosegundo.com.br', service: 'Fotografia Escolar Phygital' },
  { email: 'membro8@fotosegundo.com.br', service: 'Foto Impressa' },
  { email: 'membro9@fotosegundo.com.br', service: 'Retrato Corporativo (LinkedIn)' },
  { email: 'membro10@fotosegundo.com.br', service: 'Cobertura de Shows e Esportes' }
];

test.describe('Stress Test: Fluxo de Pagamento Multi-Membro', () => {

  for (const member of MEMBERS) {
    test(`Membro ${member.email} processando serviço: ${member.service}`, async ({ page }) => {
      const clientName = `CLIENTE-${member.email.split('@')[0].toUpperCase()}`;
      const clientEmail = generateTestEmail(5);

      console.log(`[STRESS] Starting flow for ${member.email} with service ${member.service}`);

      // ── Step 1: Login do Membro ──
      console.log(`[STRESS] Login as ${member.email}`);
      await page.goto('/login');
      await page.locator('input[type="email"]').fill(member.email);
      await page.locator('input[type="password"]').fill('123456');
      await page.getByRole('button', { name: /ENTRAR/i }).click();
      await expect(page).toHaveURL(/.*(admin|profissional|minha-conta|unidade-fixa)/, { timeout: 20000 });

      // ── Step 2: Inicia "Venda Rápida" pelo Cockpit ──
      console.log(`[STRESS] Starting Venda Rápida for ${member.service}`);
      
      if (member.email.includes('membro6')) {
        // Admin Flow
        await page.goto('/admin');
        await page.getByRole('button', { name: /Venda Rápida/i }).first().click();
      } else {
        // Professional Flow
        await page.getByRole('button', { name: /INICIAR OPERAÇÃO/i }).first().click();
      }

      // Preenche os dados da Venda Rápida
      await expect(page.getByText(/Venda Rápida|Novo Pedido/i)).toBeVisible({ timeout: 15000 });
      
      // Seleciona o cliente (Pode ser um campo de busca ou novo cliente)
      const nameInput = page.getByPlaceholder(/Nome do Cliente/i).first();
      if (await nameInput.isVisible()) {
        await nameInput.fill(clientName);
        await page.locator('input[type="email"]').last().fill(clientEmail);
      }

      // Seleciona o serviço
      await page.getByText(member.service, { exact: false }).first().click();
      
      // Finaliza e Gera Pagamento
      await page.getByRole('button', { name: /GERAR PAGAMENTO|FINALIZAR/i }).first().click();
      
      // Valida que o checkout foi gerado
      await expect(page.getByText(/Pix|Cartão|Pagamento/i).first()).toBeVisible({ timeout: 25000 });
      console.log(`[STRESS] ✅ Quick Sale and Payment generated by ${member.email}`);


      // Clica no orçamento do cliente usando Regex para evitar quebra por Case Sensitivity
      const quoteRow = page.getByText(new RegExp(clientName, 'i')).first();
      await expect(quoteRow).toBeVisible({ timeout: 25000 });
      await quoteRow.click();

      // Precifica e Aprova (Aba 5 - Fechamento)
      await page.getByRole('button', { name: '5. Fechamento' }).click();
      const priceInput = page.getByRole('spinbutton').last();
      await priceInput.fill('10'); // R$ 10,00 para o teste
      await page.keyboard.press('Tab');
      
      const approveBtn = page.getByRole('button', { name: /DISPARAR ORÇAMENTO OFICIAL/i });
      await expect(approveBtn).toBeEnabled();
      await approveBtn.click();

      // Valida sucesso
      await expect(page.getByText(/sucesso|enviado|aprovado/i).first()).toBeVisible();
      console.log(`[STRESS] ✅ Service approved by ${member.email}`);

      // ── Step 3: Valida link de pagamento ──
      // Em um fluxo real, o cliente receberia o link. Aqui vamos simular o acesso ao checkout do pedido
      console.log(`[STRESS] 🎉 Flow completed for ${member.email}`);
    });
  }

});
